### PR TITLE
build(request): replace request and request-promise with axios

### PR DESCRIPTION
**Pull request by surajrai-dzango**

### CODE REVIEW

**Comment by arvind-agarwal** [comment]
Hi @surajrai-dzango  thanks for the PR. What is the motivation behind this PR?

**Comment by surajrai-dzango** [comment]
> Hi @surajrai-dzango thanks for the PR. What is the motivation behind this PR?

@arvind-agarwal Due to the high security vulnerability, I replaced request and request-promise-native with axios. 
And also the request-promise-native is no longer maintained & deprecated.

```
  High               Prototype Pollution in lodash                                 
  Package         lodash              
                                        
  Dependency of    node_extra_ca_certs_mozilla_bundle       
                                                                          
  Path            node_extra_ca_certs_mozilla_bundle > request-promise-native   
                      > request-promise-core > lodash                               
                                                         
  More info       https://github.com/advisories/GHSA-p6mc-m468-83gw  
  ```

**Comment by arvind-agarwal** [comment]
Can you also bump the version to 1.0.5 @surajrai-dzango

**Comment by surajrai-dzango** [comment]
> Can you also bump the version to 1.0.5 @surajrai-dzango

@arvind-agarwal Done.

**Review by arvind-agarwal — COMMENTED** [review]
Test_bundle check for bad certificate is removed, can you add that also with axios? If the certificates don’t do there job the test is supposed to crash..

**Comment by surajrai-dzango** [comment]
> Test_bundle check for bad certificate is removed, can you add that also with axios? If the certificates don’t do there job the test is supposed to crash..

Hi @arvind-agarwal ,
I updated based on your suggestion. Could you please review my PR?

**Review by arvind-agarwal — APPROVED** [review]

**Pull request merged**
